-- AlterTable
ALTER TABLE "Registry" ALTER COLUMN "received" SET DATA TYPE TEXT,
ALTER COLUMN "loan_returned" SET DATA TYPE TEXT,
ALTER COLUMN "withdrawal" SET DATA TYPE TEXT,
ALTER COLUMN "expense" SET DATA TYPE TEXT,
ALTER COLUMN "balance" SET DATA TYPE TEXT,
ALTER COLUMN "total_from_bookbang" SET DATA TYPE TEXT;
