import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import SessionProvider from './components/SessionProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "STSP-EASY",
  description: "Generated by create next app",
  
};


export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider></body>
      <link rel="icon" type="png" href="/icon.png" priority={true}/>
    </html>
  );
}
